services:
  - type: web
    name: cn334-backend
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Backend/Dockerfile         #  path ถูกต้องแล้ว
    buildFilterPath: Backend                   #  ต้องใส่เพื่อให้ COPY . . ใช้ context เป็น /Backend
    envVars:
      - key: POSTGRES_DB
        value: postgres_cn334_final_project
      - key: POSTGRES_USER
        value: postgres_cn334_final_project_user
      - key: POSTGRES_PASSWORD
        value: aeafa3YAzIeYMxees6adnY22EEY8TVOC
      - key: POSTGRES_HOST
        value: dpg-d0jjbp63jp1c73a0gm7g-a
      - key: POSTGRES_PORT
        value: 5432
      - key: SECRET_KEY
        value: thisIsSecretKEY555

  - type: web
    name: cn334-frontend
    env: docker
    dockerfilePath: Frontend/Dockerfile
    buildFilterPath: Frontend                  #  สำคัญสำหรับ frontend ด้วยเช่นกัน
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://cn334-backend.onrender.com/api
