services:
  - type: web
    name: cn334-backend
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Backend/Dockerfile
    envVars:
      - key: POSTGRES_DB
        value: postgres_cn334_final_project
      - key: POSTGRES_USER
        value: postgres_cn334_final_project_user
      - key: POSTGRES_PASSWORD
        value: aeafa3YAzIeYMxees6adnY22EEY8TVOC
      - key: POSTGRES_HOST
        value: dpg-d0jjbp63jp1c73a0gm7g-a
      - key: POSTGRES_PORT
        value: 5432
      - key: SECRET_KEY
        value: thismyVerySecretKey555

  - type: web
    name: cn334-frontend
    env: docker
    region: singapore
    dockerfilePath: Frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://cn334-backend.onrender.com/api

